name: Build
on:
  - pull_request
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64

          - os: macos-latest
            goos: darwin
            goarch: amd64
          
          - os: windows-latest
            goos: windows
            goarch: 386
            cgo-enabled: 0
            extension: .exe
          - os: windows-latest
            goos: windows
            goarch: amd64
            cgo-enabled: 0
            extension: .exe
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.goos }}-${{ matrix.goarch }}
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      CGO_ENABLED: ${{ matrix.cgo-enabled }}
    steps:
      - name: Install libfuse (Linux)
        if: ${{ matrix.goos == 'linux' }}
        run: sudo apt-get install libfuse-dev

      - name: Install osxfuse (Mac)
        if: ${{ matrix.goos == 'darwin' }}
        run: brew cask install osxfuse

      - name: Install WinFsp (Windows)
        if: ${{matrix.goos == 'windows' }}
        run: choco install winfsp

      - name: Install Go
        uses: actions/setup-go@v2

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build -o dist/kubefs-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.extension }} .

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: kubefs-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.extension }}
          path: dist/kubefs-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.extension }}
