name: Build
on:
  - pull_request
jobs:
  build:
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: darwin
            goarch: amd64
      fail-fast: false
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Cache go modules
        uses: actions/cache@v1
        with:
          key: go-mod-cache
          path: ~/go/pkg/mod

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -o dist/kubefs-${{ matrix.goos }}-${{ matrix.goarch }} .

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: kubefs-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/kubefs-${{ matrix.goos }}-${{ matrix.goarch }}
